on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Hello world action        
        env:
          super_secret: ${{ secrets.SuperSecret }}
          super_secret_2: ${{ secrets.SuperSecret2 }}
        run: |
          echo "Super secret ist \"$(echo ${super_secret} | sed 's/./& /g')\""
          echo "Super secret 2 ist \"$(echo ${super_secret_2} | sed 's/./& /g')\""
