on:
  workflow_dispatch:
  push: 
    branches:
      - main
  
jobs:
  test:
    runs-on: ubuntu-latest
    environment: protected_build
    steps:
      - name: Hello world action        
        env:
          super_secret: ${{ secrets.SuperSecret }}
          super_secreter: ${{ secrets.SuperSecreter }}
        run: |
          echo "Super secret ist \"$(echo ${super_secret} | sed 's/./& /g')\""
          echo "Super secreter ist \"$(echo ${super_secreter} | sed 's/./& /g')\""
