on:
  workflow_call:
  
jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Hello world action        
        env:
          super_secret: ${{ secrets.SuperSecret }}
        run: echo "Super secret ist \"${super_secret}\""
